# Generated by Django 4.1.3 on 2022-11-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolists',
            old_name='description',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todolists',
            name='title',
        ),
    ]
